version: '3.9'  

services:
  proyecto-service:
    image: node:20  
    working_dir: /app
    volumes:
      - .:/app  
      - /app/node_modules  
    ports:
      - "4001:4001"  
    environment:
      - DATABASE_URL = mongodb+srv://mbautistarubiano:eUeWSbAl27y0N41r@cluster0.iprxl9c.mongodb.net/
      - NODE_ENV=development  
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
